### ISSUE TITLE
java.lang.ClassCastException: org.mozilla.javascript.UniqueTag

### ISSUE THREAD

**Issue by mkotsbak** [widok/todomvc#3]
I tried to clone this repository and run "sbt run" and the run fails with this stacktrace:

[info] Running org.widok.todomvc.Application
java.lang.ClassCastException: org.mozilla.javascript.UniqueTag cannot be cast to org.mozilla.javascript.Scriptable
	at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$lazifyScalaJSFields$2.apply(ScalaJSCoreLib.scala:154)
	at org.scalajs.jsenv.rhino.ScalaJSCoreLib$$anonfun$lazifyScalaJSFields$2.apply(ScalaJSCoreLib.scala:153)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at org.scalajs.jsenv.rhino.ScalaJSCoreLib.lazifyScalaJSFields(ScalaJSCoreLib.scala:153)
	at org.scalajs.jsenv.rhino.ScalaJSCoreLib.insertInto(ScalaJSCoreLib.scala:48)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$loadClasspath$2.apply(RhinoJSEnv.scala:329)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$loadClasspath$2.apply(RhinoJSEnv.scala:329)
	at scala.Option.foreach(Option.scala:236)
	at org.scalajs.jsenv.rhino.RhinoJSEnv.loadClasspath(RhinoJSEnv.scala:329)
	at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:149)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:60)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:373)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$38$$anonfun$apply$24$$anonfun$apply$25.apply(ScalaJSPluginInternal.scala:433)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$38$$anonfun$apply$24$$anonfun$apply$25.apply(ScalaJSPluginInternal.scala:427)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

**Comment by tindzk** [comment]
This seems to be an upstream bug. Would you mind reporting it [here](https://github.com/scala-js/scala-js)?

**Comment by mkotsbak** [comment]
Done. I am able to build the project and open the resulting file in a browser using "sbt fastOptJS".

**Comment by tindzk** [comment]
Thanks! How did you build it before?

**Comment by mkotsbak** [comment]
I just assumed it was Play based and tried "sbt run".

**Comment by mkotsbak** [comment]
Seems from https://github.com/scala-js/scala-js/issues/1774#issuecomment-117686451 that the build file should be improved?

**Comment by tindzk** [comment]
These flags may indeed be risky during development and therefore should only be enabled for deployments. However, for this TodoMVC application there is not going to be any impact on the performance, so they are safe to remove. For a larger project, you could have a look at the `Build.scala` of the [skeleton project](https://github.com/widok/skeleton/blob/master/project/Build.scala#L27).
